feat: make app_id a public API
dominodatalab/python-domino pull request #137
Opened 2022-07-14 09:42 UTC by maartenbreddels

Fixes #127

2022-07-14 09:55 UTC, maartenbreddels commented
Fixes #128 

I decided to push two commits to this PR, since the seconds depends on the first.

2022-07-26 17:22 UTC, ddl-olsonJD commented
Hey @maartenbreddels I will be looking into this. 
Do you also have some test cases for this?

2022-07-26 19:50 UTC, maartenbreddels commented
Hi,

Happy to add them!
let me know what kind of test I could use as a template.

Regards,

Maarten

2022-07-27 13:47 UTC, ddl-olsonJD requested changes
And for tests, you can follow the test suites that we already have, but around app publishing and un-publishing

2022-07-27 13:47 UTC, ddl-olsonJD commented on domino/domino.py
> +    def app_id(self):
Set as a property as well.

2022-07-27 13:47 UTC, ddl-olsonJD commented on domino/domino.py
> +    def app_get_status(self, id) -> Optional[str]:
```
def def app_get_status(self, ext_app_id=None) -> Optional[str]:
    app_id = ext_app_id if ext_app_id else self.app_id
```

2022-07-27 13:47 UTC, ddl-olsonJD commented on domino/domino.py
> +        return self.__app_get_status()
meant to call `app_get_status`?

2023-01-03 17:14 UTC, ddl-olsonJD commented
[Jira Ticket - DOM-43074](https://dominodatalab.atlassian.net/browse/DOM-43074)

2024-04-16 00:54 UTC, ddl-olsonJD commented
close as out of date

2024-04-16 00:54 UTC, closed without merging