Update Model API Create with logHttpRequestResponse
dominodatalab/python-domino pull request #169
Opened 2023-03-18 18:41 UTC by ddl-wasanthag

### Link to JIRA

[[DOM-XYZ](https://dominodatalab.atlassian.net/browse)](https://onedominodatalab.atlassian.net/browse/PS-6544)

### What issue does this pull request solve?

Currently, Python API does not support enabling Model API HTTP request and response logging.

### What is the solution?

Introduce enabling Model API HTTP requests and responses via the python library.

### Testing

I have tested this by enabling the Log HTTP Request and responses with Pythion code. Then issue curl commands and observe the requests and responses are logged 
- [ ] Unit test(s)

### Pull Request Reminders

- [ ] Has relevant documentation been updated?
- [ ] Does the code follow [Python Style Guide] (https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html)
- [ ] Update the [changelog](https://github.com/dominodatalab/python-domino/blob/master/CHANGELOG.md)
- [ ] Are the existing unit tests still passing?
- [ ] Have new unit tests been added to cover any changes to the code?
- [ ] Has the JIRA ticket(s) been linked above?

### References (optional)

2023-03-20 13:29 UTC, ddl-olsonJD commented
@ddl-wasanthag Thanks for this updates. 
Can you update these 2 files as well as check the **Pull Request Reminders**
- tests/test_models.py
- examples/models_and_environments.py

2023-03-20 13:30 UTC, ddl-olsonJD requested changes
@ddl-wasanthag Thanks for this updates. 
Can you update these 2 files as well as check the **Pull Request Reminders**
- tests/test_models.py
- examples/models_and_environments.py

2023-03-20 14:37 UTC, ddl-olsonJD requested changes

2023-03-20 21:54 UTC, ddl-wasanthag commented on domino/domino.py
>      def model_publish(
It is optional. let me update that and add the PR reminders. Thank You.

2023-03-20 22:10 UTC, ddl-olsonJD commented on domino/domino.py
> +        self, file, function, environment_id, name, description, logHttpRequestResponse, files_to_exclude=None
Add default value if logHttpRequestResponse not required?

2024-04-16 12:15 UTC, ddl-wasanthag commented
I will close this PR for now and reopen it later with the necessary changes.

2024-04-16 12:15 UTC, closed without merging